export default {
    UnlockPrice: 'Unlock price',
    UnlockBlueprints: 'Unlock blueprints',
    UnlockTime: 'Unlock Time',
    WhiteStarScore: 'WS But',
    BSScore: 'BS But',
    hyd: 'hyd',
    AU: 'AU',
    days: 'd',
    hours: 'h',
    min: 'min',
    sec: 'sec',
    WS: 'WS',
    BS: 'BS',
    typeModTrade: 'Modules déchange',
    typeModMining: 'Modules miniers',
    typeModWeapon: 'Modules darmes',
    typeModShield: 'Modules de blindage',
    typeModSupport: 'Modules de support',
    lvl: 'niveau',
    home: 'Home',
};
