exports.default = {
    en: {
        UnlockPrice: 'Unlock price',
        UnlockBlueprints: 'Unlock blueprints',
        UnlockTime: 'Unlock Time',
        WhiteStarScore: 'WS Score',
        BSScore: 'BS Score',
        hyd: 'hyd',
        AU: 'AU',
        days: 'd',
        hours: 'h',
        min: 'min',
        sec: 'sec',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Trade modules',
        typeModMining: 'Mining modules',
        typeModWeapon: 'Weapon modules',
        typeModShield: 'Shield modules',
        typeModSupport: 'Support modules',
        lvl: 'lvl',
        home: 'Home',
        content: 'Content',
        UpgradeCost: 'Upgrade Cost',
        UpgradeTime: 'Upgrade time',
        NewModuleSlots: 'Type of additional new slot',
        InitialModuleLevels: 'Module level',
        MaxPerStarSystem: 'Maximum quantity per system',
        DisableTime: 'Disable time',
        cerbShield: 'Cerberus shield',
        cerbWeapon: 'Cerberus weapons',
        cerbModule: 'Cerberus module',
        cerberus: 'Cerberus',
        sections: 'Sections',
        flagshipModules: 'Flagship modules',
        Cost: 'Cost',
        PlanetTypes: 'Planet Types',
        HydrogenPerDay: 'New hydro every day',
        sectors: 'Sectors',
        colonizationPlanets: 'Colonization of planets',
        lvlsPlanets: 'Planet improvement',
        XPAward: 'XP Award',
        TimeToUpgrade: 'Time Upgrade',
        MaxShipments: 'Max Shipments',
        CreditShipmentModifier: 'Shipment modifier',
        MaxUpgradeLevel: 'Max Level',
        planets: 'Planets',
        stars: 'Stars',
        ShipmentsCRValuePerDay: 'Base Shipments Cost Per Day',
        Model: 'Model',
        SlotsUsed: 'Weight',
        SalvageCRReward: 'Credits for Salvage',
        SalvageHydroReward: 'Hydrogen behind Salvage',
        PriceInCrystals: 'Buying for crystals',
        CombatArt: 'Orb',
        UtilityArt: 'Blue crystal',
        SupportArt: 'Tetrahedron',
        blueprints: 'Blueprints drop for each level',
        MaxInfluenceGain: 'Max. influence reward',
        MaxInfluenceLoss: 'Max. influence loss',
        InfluenceAwardThreshold: 'Actions for gaining influence',
        NumMaxPlanets: 'The number of max. planets',
        NumPlayersWithAccess: 'Number of players',
        GhostSpawnSecs: 'Ghost Spawn',
        ResearchSlots: 'Number of slots for artifacts',
        MinPlayerLevel: 'Min. player level',
        TimeLimitDays: 'Days to complete',
        artLevel: 'Artifact level',
        MinRSLevel: 'Min. level RS',
        MaxRSLevel: 'Max. level RS',
        module: 'Module',
        IntParam: 'Value X',
        MoveUpdateSec: 'Move delay',
        BlueStar_CRRewardRate: 'Compensation from the cost of the battleship',
        BlueStar_CRRewardWinLimitPeriod: 'Cooldown rewards',
        BlueStar_MaxHydroPerDayPct: 'Maximum Hydrogen Reward',
        BlueStar_HydroPctPerPos: 'Hydrogen reward percent of tank',
        BlueStar_Fragments: 'Fragments per position',
        StarSectorDPS: 'Star damage',
        WSBucketSizes: 'Mode',
        ScoreNThresholds: 'Actions for Tick',
        WSMaxBSPerPlayer: 'Maximum battleships per player',
        WSMaxOtherPerPlayer: 'Maximum ships of another type per player',
        WSLostBSTimeCooldown: 'Cooldown lost battleship',
        WSLostOtherTimeCooldown: 'Cooldown lost ships of another type',
        WSJumpBSTimeCooldown: 'Cooldown after the jump battleship',
        WSJumpOtherTimeCooldown: 'Cooldown after jumping another type of ship',
        WSScoreDamageModifier: 'WS score battle modifier',
        WSScoreMiningModifier: 'WS score mining modifier',
        WSScoreTransportModifier: 'WS score transportation modifier',
        SafeInterceptorInPublicRS: 'Neutral Interceptors on Public RS',
        NoCerbBondTeleportPRS: 'Deny use of Cerberus + Bond + Teleport on Public RS',
        PubRSEMPReqEnemies: 'Enemy in EMP zone is required before activation in the Public RS',
        TID_Artifact: 'Artifact',
        OnDestroySpawnCount: 'A number of spawn ships after destroy',
        BarrageMaxAdditionalEnemies: 'Max. enemies for additional damage',
        DroneShipmentBonusMax: 'Max. bonus',
        TeleportBreaksBond: 'Teleport breaks the Bond',
        LeapBreaksBond: 'Leap breaks the Bond',
        DestinyBreaksBond: 'Destiny breaks the Bond',
        BondBreaksBond: 'Bond breaks the Bond',
        BondOverridesBarrier: 'Bond ignores the Barrier',
        UnityMaxDamageIncreasePct: 'Max. damage',
        MaxShips: 'Max. ships',
        ShipToSpawn: 'Ship spawn'

    },
    ru: {
        UnlockPrice: 'Стоимость изучения',
        UnlockBlueprints: 'Требуется чертежей',
        UnlockTime: 'Время изучения',
        WhiteStarScore: 'БЗ очки',
        BSScore: 'ГЗ очки',
        hyd: 'вод',
        AU: 'АЕ',
        days: 'д',
        hours: 'ч',
        min: 'мин',
        sec: 'сек',
        WS: 'БЗ',
        BS: 'ГЗ',
        typeModTrade: 'Модули торговли',
        typeModMining: 'Модули добычи',
        typeModWeapon: 'Оружейные модули',
        typeModShield: 'Модули щитов',
        typeModSupport: 'Модули поддержки',
        lvl: 'ур',
        home: 'На главную',
        content: 'Содержание',
        UpgradeCost: 'Стоимость улучшения',
        UpgradeTime: 'Время улучшения',
        NewModuleSlots: 'Тип дополнительного нового слота',
        InitialModuleLevels: 'Уровень модуля',
        MaxPerStarSystem: 'Максимальное количество на систему',
        DisableTime: 'Время отключения',
        cerbShield: 'Щит Цербера',
        cerbWeapon: 'Оружие Цербера',
        cerbModule: 'Модуль Цербера',
        cerberus: 'Церберы',
        Sections: 'Разделы',
        flagshipModules: 'Модули флагмана',
        Cost: 'Стоимость',
        SectorUnlockTime: 'Время открытия сектора',
        PlanetTypes: 'Типы планет',
        HydrogenPerDay: 'Новый водород каждый день',
        sectors: 'Сектора',
        colonizationPlanets: 'Колонизация планет',
        lvlsPlanets: 'Улучшение планет',
        XPAward: 'Опыт',
        TimeToUpgrade: 'Время улучшения',
        MaxShipments: 'Макс. грузов',
        CreditShipmentModifier: 'Модификатор грузов',
        MaxUpgradeLevel: 'Макс. уровень',
        planets: 'Планеты',
        stars: 'Звёзды',
        ShipmentsCRValuePerDay: 'Базовая стоимость грузов в день',
        Model: 'Модель',
        SlotsUsed: 'Вес',
        SalvageCRReward: 'Кредиты за утилизацию',
        SalvageHydroReward: 'Водород за утилизацию',
        PriceInCrystals: 'Покупка за кристаллы',
        CombatArt: 'Сфера',
        UtilityArt: 'Синий кристалл',
        SupportArt: 'Тетраэдр',
        blueprints: 'Выпадение чертежей для каждого уровня',
        MaxInfluenceGain: 'Макс. влияния за победу',
        MaxInfluenceLoss: 'Макс. влияния за проигрыш',
        InfluenceAwardThreshold: 'Действия для получения влияния',
        NumMaxPlanets: 'Число макс. планет',
        NumPlayersWithAccess: 'Количество игроков',
        GhostSpawnSecs: 'Спавн «Призраков» Цербера',
        ResearchSlots: 'Количество слотов для артефактов',
        MinPlayerLevel: 'Мин. уровень игрока',
        TimeLimitDays: 'Дней на завершение',
        artLevel: 'Уровень артефакта',
        MinRSLevel: 'Мин. уровень КЗ',
        MaxRSLevel: 'Макс. уровень КЗ',
        module: 'Модуль',
        IntParam: 'Значение X',
        MoveUpdateSec: 'Задержка движения',
        BlueStar_CRRewardRate: 'Компенсация от стоимости линкора',
        BlueStar_CRRewardWinLimitPeriod: 'Перезарядка наград',
        BlueStar_MaxHydroPerDayPct: 'Максимальное вознаграждение за водород',
        BlueStar_HydroPctPerPos: 'Процент вознаграждения водородом от бака',
        BlueStar_Fragments: 'Фрагменты на позицию',
        StarSectorDPS: 'Урон звезды',
        WSBucketSizes: 'Режим',
        ScoreNThresholds: 'Действия за Тик',
        WSMaxBSPerPlayer: 'Максимум линкоров на игрока',
        WSMaxOtherPerPlayer: 'Максимальное количество кораблей другого типа на игрока',
        WSLostBSTimeCooldown: 'Перезарядка потерянного линкора',
        WSLostOtherTimeCooldown: 'Перезарядка потерянных кораблей другого типа',
        WSJumpBSTimeCooldown: 'Перезарядка после прыжка линкором',
        WSJumpOtherTimeCooldown: 'Перезарядка после прыжка другим типом корабля',
        WSScoreDamageModifier: 'WS Score модификатор битвы за',
        WSScoreMiningModifier: 'WS Score модификатор добычи',
        WSScoreTransportModifier: 'WS Score модификатор транспортировки',
        SafeInterceptorInPublicRS: 'Нейтральные Перехватчики на общедоступных КЗ',
        NoCerbBondTeleportPRS: 'Запретить использование Цербера + Узы + Телепорт на общедоступной КЗ',
        PubRSEMPReqEnemies: 'Враг в зоне ЭМИ требуется перед активацией в общедоступной КЗ',
        TID_Artifact: 'Артефакт',
        OnDestroySpawnCount: 'Количество появившихся кораблей после уничтожения',
        BarrageMaxAdditionalEnemies: 'Макс. врагов для доп. урона',
        DroneShipmentBonusMax: 'Макс. бонус',
        TeleportBreaksBond: 'Телепорт ломает Узы',
        LeapBreaksBond: 'Скачок ломает Узы',
        DestinyBreaksBond: 'Рок ломает Узы',
        BondBreaksBond: 'Узы ломают Узы',
        BondOverridesBarrier: 'Узы игнорируют Барьер',
        UnityMaxDamageIncreasePct: 'Макс. урон',
        MaxShips: 'Макс. кораблей',
        ShipToSpawn: 'Спавн корабля'
    },
    de: {
        UnlockPrice: 'Preis freischalten',
        UnlockBlueprints: 'Schalte Blaupausen frei',
        UnlockTime: 'Zeit entsperren',
        WhiteStarScore: 'WS Ergebnis',
        BSScore: 'BS Ergebnis',
        hyd: 'hyd',
        AU: 'AU',
        days: 't',
        hours: 's',
        min: 'p',
        sec: 'z',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Handelsmodule',
        typeModMining: 'Mining-Module',
        typeModWeapon: 'Waffenmodule',
        typeModShield: 'Abschirmmodule',
        typeModSupport: 'Unterstützungsmodule',
        lvl: 'Niveau',
        home: 'Home',
        content: 'Inhalt'
    },
    es: {
        UnlockPrice: 'Precio de desbloqueo',
        UnlockBlueprints: 'Desbloquear planos',
        UnlockTime: 'Tiempo de desbloqueo',
        WhiteStarScore: 'WS Puntuación',
        BSScore: 'BS Puntuación',
        hyd: 'hyd',
        AU: 'AU',
        days: 'd',
        hours: 'h',
        min: 'min',
        sec: 'sec',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Módulos comerciales',
        typeModMining: 'Módulos de minería',
        typeModWeapon: 'Módulos de armas',
        typeModShield: 'Módulos de protección',
        typeModSupport: 'Módulos de soporte',
        lvl: 'nivel',
        home: 'Home',
        content: 'Contenido'
    },
    it: {
        UnlockPrice: 'Sblocca prezzo',
        UnlockBlueprints: 'Sblocca progetti',
        UnlockTime: 'Sblocca tempo',
        WhiteStarScore: 'WS Punto',
        BSScore: 'BS Punto',
        hyd: 'hyd',
        AU: 'AU',
        days: 'g',
        hours: 'o',
        min: 'min',
        sec: 'sec',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Moduli commerciali',
        typeModMining: 'Moduli di data mining',
        typeModWeapon: 'Moduli arma',
        typeModShield: 'Moduli schermati',
        typeModSupport: 'Moduli di supporto',
        lvl: 'livello',
        home: 'Home',
        content: 'Soddisfare'
    },
    fr: {
        UnlockPrice: 'Unlock price',
        UnlockBlueprints: 'Unlock blueprints',
        UnlockTime: 'Unlock Time',
        WhiteStarScore: 'WS But',
        BSScore: 'BS But',
        hyd: 'hyd',
        AU: 'AU',
        days: 'd',
        hours: 'h',
        min: 'min',
        sec: 'sec',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Modules déchange',
        typeModMining: 'Modules miniers',
        typeModWeapon: 'Modules darmes',
        typeModShield: 'Modules de blindage',
        typeModSupport: 'Modules de support',
        lvl: 'niveau',
        home: 'Home',
        content: 'Contenu'
    },
    jp: {
        UnlockPrice: '価格のロックを解除',
        UnlockBlueprints: 'ブループリントのロックを解除',
        UnlockTime: 'ロック解除時間',
        WhiteStarScore: 'WS スコア',
        BSScore: 'BS スコア',
        hyd: 'hyd',
        AU: 'AU',
        days: '日々',
        hours: '時間',
        min: '数分',
        sec: '秒',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: '取引モジュール',
        typeModMining: 'マイニングモジュール',
        typeModWeapon: '武器モジュール',
        typeModShield: 'シールドモジュール',
        typeModSupport: 'サポートモジュール',
        lvl: 'レベル',
        home: 'Home',
        content: 'コンテンツ'
    },
    ko: {
        UnlockPrice: '가격 잠금 해제',
        UnlockBlueprints: '청사진 잠금 해제',
        UnlockTime: '잠금 해제 시간',
        WhiteStarScore: 'WS 점수',
        BSScore: 'BS 점수',
        hyd: 'hyd',
        AU: 'AU',
        days: '일',
        hours: '시간',
        min: '의사록',
        sec: '초',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: '무역 모듈',
        typeModMining: '마이닝 모듈',
        typeModWeapon: '무기 모듈',
        typeModShield: '차폐 모듈',
        typeModSupport: '지원 모듈',
        lvl: '수평',
        home: 'Home',
        content: '함유량'
    },
    "zh-si": {
        UnlockPrice: '解锁价格',
        UnlockBlueprints: '解锁蓝图',
        UnlockTime: '解锁时间',
        WhiteStarScore: 'WS 得分了',
        BSScore: 'BS 得分了',
        hyd: 'hyd',
        AU: 'AU',
        days: '天',
        hours: '小时',
        min: '分钟',
        sec: '秒',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: '交易模块',
        typeModMining: '采矿模块',
        typeModWeapon: '武器模块',
        typeModShield: ' Shield模块',
        typeModSupport: '支持模块',
        lvl: '水平',
        home: 'Home',
        content: '内容'
    },
    pt: {
        UnlockPrice: 'Unlock price',
        UnlockBlueprints: 'Desbloquear blueprints',
        UnlockTime: 'Unlock Time',
        WhiteStarScore: 'WS Ponto',
        BSScore: 'BS Ponto',
        hyd: 'hyd',
        AU: 'AU',
        days: 'd',
        hours: 'h',
        min: 'min',
        sec: 'sec',
        WS: 'WS',
        BS: 'BS',
        typeModTrade: 'Módulos comerciais',
        typeModMining: 'Módulos de mineração',
        typeModWeapon: 'Módulos de armas',
        typeModShield: 'Blindagem de módulos',
        typeModSupport: 'Módulos de suporte',
        lvl: 'nível',
        home: 'Home',
        content: 'Conteúdo'
    }
}