export default {
    UnlockPrice: 'Sblocca prezzo',
    UnlockBlueprints: 'Sblocca progetti',
    UnlockTime: 'Sblocca tempo',
    WhiteStarScore: 'WS Punto',
    BSScore: 'BS Punto',
    hyd: 'hyd',
    AU: 'AU',
    days: 'g',
    hours: 'o',
    min: 'min',
    sec: 'sec',
    WS: 'WS',
    BS: 'BS',
    typeModTrade: 'Moduli commerciali',
    typeModMining: 'Moduli di data mining',
    typeModWeapon: 'Moduli arma',
    typeModShield: 'Moduli schermati',
    typeModSupport: 'Moduli di supporto',
    lvl: 'livello',
    home: 'Home',
    content: 'Soddisfare',
};
