export default {
    UnlockPrice: '가격 잠금 해제',
    UnlockBlueprints: '청사진 잠금 해제',
    UnlockTime: '잠금 해제 시간',
    WhiteStarScore: 'WS 점수',
    BSScore: 'BS 점수',
    hyd: 'hyd',
    AU: 'AU',
    days: '일',
    hours: '시간',
    min: '의사록',
    sec: '초',
    WS: 'WS',
    BS: 'BS',
    typeModTrade: '무역 모듈',
    typeModMining: '마이닝 모듈',
    typeModWeapon: '무기 모듈',
    typeModShield: '차폐 모듈',
    typeModSupport: '지원 모듈',
    lvl: '수평',
    home: 'Home',
    content: '함유량',
};
