name: Bug report [Ukrainian language]
description: Create a report to help us improve
title: "[Bug] Bug report (Turkish language)"
labels: ["bug", "i18n"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
