import YAML from 'yaml';

export default {
  js: {
    opts: {
      parser: 'babel',
      trailingComma: 'all',
      printWidth: 410, // чтоб массивы выстраивались в одну линию
    },
    formatting(content, pluginName, addData) {
      return `
      // generated by GenerateGameData ${pluginName}

      let data = ${JSON.stringify(content, null, 2)}

      ${addData.content || ''}

      export {${addData.export}}
      `;
    },
  },
  json: {
    opts: {
      parser: 'json',
      trailingComma: 'es6',
      printWidth: 410,
    },
    formatting(content) {
      return JSON.stringify(content, null, 2);
    },
  },
  yaml: {
    opts: {
      parser: 'yaml',
      printWidth: 410,
    },
    formatting(content, pluginName) {
      let str = `# generated by GenerateGameData ${pluginName}\n\n`;
      const doc = new YAML.Document(content);

      // чтоб массивы выстраивались в одну линию
      Object.keys(content).forEach((key) => {
        Object.keys(content[key]).forEach((k) => {
          if (Array.isArray(content[key][k])) {
            doc.getIn([key, k]).type = 'FLOW_SEQ';
          }
        });
      });
      str += String(doc);
      return str;
    },
  },
};
