// noinspection SpellCheckingInspection

export default [

    // meta
    'Name',
    'Name2',
    'TID',
    'TID2',
    'TID_Description',

    // MODULES
    'UnlockBlueprints',
    'UnlockPrice',
    'UnlockTime',
    // ----------------
    'ActivationDelay',
    'EffectDurationx10',
    'EffectDurationx10WS',
    'EffectDurationx10BS',
    'EffectRadius',
    'EffectRadiusWS',
    'EffectRadiusBS',
    'RedStarLifeExtentionRS',
    'AOEDamage',
    'AOEDamage_WS',
    'AOEDamage_BS',
    'RedStarLifeExtention',
    'RepairHullPointsPerSecond',
    'TimeWarpFactor',
    'TimeWarpSuppression',
    'ExtraTradeSlots',
    'WaypointShipmentRewardBonus',
    'JobPayoutIncreasePercent',
    'SpeedIncreasePerShipment',
    'TradeBurstShipmentsStart',
    'TradeBurstShipmentBonus',
    'SpawnCapacity',
    'RSLESec',
    'DroneDeliveryBonus',
    'TradeStationDeliverReward',
    'TeleportShipments',
    'SpeedIncreasePerArtifact',
    'SpeedIncreasePerRelic',
    'ArtifactBoostPct',
    'DroneHydro',
    'ActivationHydro',
    'APTPIOTTP',
    'APTPIOTTPYS',
    'APTPIOTTPRS',
    'APTPIOTTPWS',
    'RushYSHydroDc',
    'RushRSHydroDc',
    'RushRSSpeedIncr',
    'RushWSSpeedIncrPR',
    'MiningSpeedModifierPct',
    'MiningSpeedModifierPct_YS',
    'MiningSpeedModifierPct_RS',
    'MiningSpeedModifierPct_WS',
    'HydroDeliveryBonusYS',
    'HydroDeliveryBonusWS',
    'MassMiningTotalAsteroids',
    'ActivationHydroOnBoard',
    'HydroDeliveryBonus',
    'MassMiningExtraAsteroids',
    'RSLESecPer500Hydro',
    'ExtraHydroStorage',
    'IncreaseSectorHydroPct',
    'IncreaseSectorHydroPct_RS',
    'HydroUploadPct',
    'HydroClonePct',
    'InstantHydrogenCollected',
    'MaxNewAsteroids',
    'MaxNewHydro_YS',
    'MaxNewHydro_RS',
    'MaxNewHydro_WS',
    'CrunchYS',
    'CrunchRS',
    'CrunchWS',
    'OnBoardHydroMax',
    'RSLESecPer500HydroRS',
    'DPS',
    'DPH_WS',
    'DPS_BS',
    'MaxTargets',
    'AdditionalDPSPerTargetInRange',
    'AddDPSPerTarget',
    'AddDPSPerTarget_BLS',
    'AddDPSPerTarget_WS',
    'ShieldStrength',
    'SpeedIncrDuringActivation',
    'MirrorDamageAsAOE',
    'MotionShieldPct',
    'ActivationPrepWS',
    'RepairHullPointsPerSecond_BLS',
    'RepairHullPointsPerSecond_WS',
    'SolitudeDPSBoost',
    'DmgReduceImmobilize',
    'ShieldStrengthPVE',
    'ShieldStrengthPvP',
    'SalvageAmount',
    'SalvageAmountRS',
    'SalvageAmountWS',
    'ImpulseDPS_RS',
    'ImpulseDPS_PVP',
    'SpeedSlowdownFactor',
    'WSDispatchAOEAmt',
    'LeapAOEAmt',
    'LinkDPSBoost',
    'LinkDPSBoostWS',
    'AdditionalRangesPerLink',
    'SolitudeDPSBoost_RS',
    'SolitudeDPSBoost_PVP',
    'FortifyDamageAmpFactor_RS',
    'FortifyDamageAmpFactor_PVP',
    'DamageAmplifyFactor_PVE',
    'DamageAmplifyFactor_PVP',
    'DamageReduceFactor_PVE',
    'LeapAOEAmtPvP',
    'LeapAOEAmtPvE',
    'MovementSlowdown',
    'MovementSlowdown',
    // ------------------
    'FuelUseIncrease',
    'ActivationFuelCost',
    'BCCost',
    'WhiteStarScore',
    'BSScore',

    // YELLOW_STAR
    'MinScannerLevel',
    'PlanetTypes',
    'AsteroidsMax',
    'HydrogenPerDay',
    'CerbGroup',
    'BSAnomaly',
    'DSAnomaly',
    'BaseType',

    'YSCommonVariations',
    'MaxUpgradeLevel',
    'CreditIncomeModifier',
    'FuelIncomeModifier',
    'CreditStorageModifier',
    'FuelStorageModifier',
    'CreditShipmentModifier',
    'ShipmentsPerHour',

    'Cost',
    'TimeToUpgrade',
    'CreditStorage',
    'FuelStorage',
    'MaxShipments',
    'CreditsPerHour',
    'FuelPerHour',
    'ShipmentsCRValuePerDay',
    'XPAward',
    'RSLevelReq',

    // RED_STAR
    'Hydrogen',
    'Credits',
    'SalvageCRReward',
    'SalvageHydroReward',
    'SlotsUsed',
    'TimeToLoad',
    'TimeToResearch',
    'XP',
    'PriceInCrystals',
    'RushCostModifier',
    'DRSPoints',
    'InfluencePoints',

    // WHITE_STARS
    'WSBucketSizes',
    'Thresholds',
    'ExtraAsteroidSpawnTick',
    'ExtraAsteroidSpawnRingDistance',
    'ExtraAsteroidSpawnAmt',

    // 'RedStarDisplayLevel', // сортировка закинет наверх
    'TicksPerRelic',
    'HydrogenForRelic',

    // SPACE_BUILDINGS
    'Cost',
    'ConstructionTime',
    // ----------------
    'ShipyardCapacity',
    'SectorUnlockCost',
    'SectorUnlockTime',
    'TotalShipmentCRPerDay',
    'TimeSpeedupFactor',
    'TeleportShipmentsPerHr',
    'TeleportShipmentsDurationHr',
    'TeleportShipmentActivationFragments',
    'RelayBonusPct',
    'FragmentCapacity',
    'TeleportShipmentMaxSectors',
    'TSHydroCost',
    'SHHydroPerDay',

    // PLAYER_GOALS
    'valueX',
    'valueY',
    'valueZ',
    'TimeLimitDays',
    'CRRewardPerDay',
    'FuelRewardPerDay',
    'MaxRSLevel',
    'MinRSLevel',

    '_',
];
