// noinspection SpellCheckingInspection

export default [

    // meta
    'Name',
    'Name2',
    'TID',
    'TID2',
    'TID_Description',

    // MODULES
    'UnlockBlueprints',
    'UnlockPrice',
    'UnlockTime',
    // ----------------
    'EffectDurationx10',
    'EffectDurationx10WS',
    'EffectDurationx10BS',
    'EffectRadius',
    'EffectRadiusWS',
    'EffectRadiusBS',
    'AOEDamage',
    'AOEDamage_WS',
    'AOEDamage_BS',
    'RedStarLifeExtention',
    'RepairHullPointsPerSecond',
    'TimeWarpFactor',
    'TimeWarpSuppression',
    'UnityBoostPercent',
    'DamageReductionPct',
    'ExtraTradeSlots',
    'WaypointShipmentRewardBonus',
    'JobPayoutIncreasePercent',
    'SpeedIncreasePerShipment',
    'TradeBurstShipmentsStart',
    'TradeBurstShipmentBonus',
    'SpawnCapacity',
    'DroneShipmentBonus',
    'DroneShipmentBonusMax',
    'TradeStationDeliverReward',
    'TeleportShipments',
    'APTPIOTTP',
    'APTPIOTTPWS',
    'MiningSpeedModifierPct',
    'ExtraMineralStorage',
    'IncreaseSectorHydroPct',
    'HydroUploadPct',
    'MaxNewAsteroids',
    'HydroPerNewAsteroid',
    'DPS',
    'MaxDPS',
    'MaxTargets',
    'AdditionalDPSPerTargetInRange',
    'ShieldStrength',
    'SpeedIncrDuringActivation',
    'MirrorDamagePct',
    // ------------------
    'FuelUseIncrease',
    'ActivationFuelCost',
    'BCCost',
    'WhiteStarScore',
    'BSScore',

    // YELLOW_STAR
    'MinScannerLevel',
    'PlanetTypes',
    'AsteroidsMax',
    'HydrogenPerDay',
    'CerbGroup',
    'BSAnomaly',
    'BaseType',

    'MaxUpgradeLevel',
    'CreditIncomeModifier',
    'FuelIncomeModifier',
    'CreditStorageModifier',
    'FuelStorageModifier',
    'CreditShipmentModifier',
    'MaxShipments',
    'ShipmentsPerHour',

    // RED_STAR
    'Hydrogen',
    'Credits',
    'SalvageCRReward',
    'SalvageHydroReward',
    'SlotsUsed',
    'TimeToLoad',
    'TimeToResearch',
    'XP',
    'PriceInCrystals',
    'InfluencePoints',

    // WHITE_STARS
    'WSBucketSizes',
    'Thresholds',
    'ExtraAsteroidSpawnTick',
    'ExtraAsteroidSpawnRingDistance',
    'ExtraAsteroidSpawnAmt',

    // 'RedStarDisplayLevel', // сортировка закинет наверх
    'TicksPerRelic',
    'HydrogenForRelic',

    // SPACE_BUILDINGS
    'Cost',
    'ConstructionTime',
    // ----------------
    'ShipyardCapacity',
    'SectorUnlockCost',
    'SectorUnlockTime',
    'TotalShipmentCRPerDay',
    'TimeSpeedupFactor',
    'TeleportShipmentsPerHr',
    'TeleportShipmentsDurationHr',
    'TeleportShipmentActivationFragments',
    'FragmentCapacity',
    'TeleportShipmentMaxSectors',
    'TSHydroCost',

    // PLAYER_GOALS
    'valueX',
    'valueY',
    'valueZ',
    'TimeLimitDays',
    'CRRewardPerDay',
    'FuelRewardPerDay',
    'MaxRSLevel',
    'MinRSLevel',

    '_',
];
