// noinspection SpellCheckingInspection

import gameCharsLocKeys from '../../i18n/configKeys/string.js';

export default {
    // by i18n/locale
    UnlockBlueprints: 'UNLOCK_BLUEPRINTS',
    UnlockPrice: 'UNLOCK_PRICE',
    UnlockTime: 'UNLOCK_TIME',
    WhiteStarScore: 'WS_SCORE',
    BSScore: 'BLS_SCORE',
    PubRSEMPReqEnemies: 'PUB_RS_EMP_REQ_ENEMIES',
    TID_Artifact: 'ARTIFACT',
    TeleportBreaksBond: 'TELEPORT_BREAKS_BOND',
    NoCerbBondTeleportPRS: 'NO_CERB_BOND_TELEPORT_PRS',
    NewModuleSlots: 'NEW_MODULE_SLOTS',
    DestinyBreaksBond: 'DESTINY_BREAKS_BOND',
    drone: 'DRONE',
    projectile: 'PROJECTILE',
    MaxPerStarSystem: 'MAX_PER_STAR_SYSTEM',
    DroneShipmentBonusMax: 'DRONE_SHIPMENT_BONUS_MAX',
    PreventUseOnWsJumpgate: 'PREVENT_USE_ON_WS_JUMPGATE',
    SectorEnrichCooldownSeconds: 'SECTOR_ENRICH_COOLDOWN_SECONDS',
    SectorGenesisCooldownSeconds: 'SECTOR_GENESIS_COOLDOWN_SECONDS',
    BarrageMaxAdditionalEnemies: 'BARRAGE_MAX_ADDITIONAL_ENEMIES',
    StopCountdownOnDisable: 'STOP_COUNTDOWN_ON_DISABLE',
    IsAreaShield: 'AREA_SHIELD',
    BSOnly: 'BS_ONLY',
    UnityMaxDamageIncreasePct: 'UNITY_MAX_DAMAGE_INCREASE_PCT',
    DisableActivationDuringPrep: 'DISABLE_ACTIVATION_DURING_PREP',
    BondOverridesBarrier: 'BOND_OVERRIDES_BARRIER',
    IgnoreBarrier: 'IGNORE_BARRIER',
    LeapBreaksBond: 'LEAP_BREAKS_BOND',
    BondBreaksBond: 'BOND_BREAKS_BOND',
    TimeWarpSuppression: 'TIME_WARP_SUPPRESSION',
    DeactivateOnJump: 'DEACTIVATE_ON_JUMP',
    HydrogenPerDay: 'HYDROGEN_PER_DAY',
    CerbGroup: 'CERBERUS',
    Cost: 'COST',
    XPAward: 'XP_AWARD',
    ShipmentsCRValuePerDay: 'SHIPMENTS_CR_VALUE_PER_DAY',
    TimeToUpgrade: 'TIME_TO_UPGRADE',
    MaxUpgradeLevel: 'MAX_UPGRADE_LEVEL',
    CreditShipmentModifier: 'CREDIT_SHIPMENT_MODIFIER',
    MaxShipments: 'MAX_SHIPMENTS',
    PlanetTypes: 'PLANET_TYPES',
    Model: 'MODEL',
    DesignUpgradeCost: 'UPGRADE_COST',
    DesignUpgradeTime: 'UPGRADE_TIME',
    ApplyAOEDamageOnDestroy: 'AOE_DAMAGE_ON_DESTROY',
    OnDestroySpawnCount: 'ON_DESTROY_SPAWN_COUNT',
    GhostSpawnSecs: 'GHOST_SPAWN_SECS',
    ShipToSpawn: 'SHIP_TO_SPAWN',
    MaxShips: 'MAX_SHIPS',
    AwardXP: 'XP_AWARD',
    RadialMoveRadius: 'MOVE_RADIUS',
    MaxOnOwnSolarSystem: 'MAX_PER_STAR_SYSTEM',
    ConstructionTime: 'UPGRADE_TIME',
    MaxPerSector: 'MAX_PER_SECTOR',
    ResearchSlots: 'RESEARCH_SLOTS',
    BuyInPairs: 'BUY_IN_PAIRS',
    TotalShipmentCRPerDay: 'SHIPMENTS_CR_VALUE_PER_DAY',
    SafeInterceptorInPublicRS: 'SAFE_INTERCEPTOR_IN_PUBLIC_RS',
    RSPublicLateJoin_TimeAvailable: 'RS_PUBLIC_LATE_JOIN_TIME_AVAILABLE',
    RSPublicLateJoin_MinStarLevel: 'RS_PUBLIC_LATE_JOIN_MIN_STAR_LEVEL',
    NumPlayersWithAccess: 'NUM_PLAYERS_WITH_ACCESS',
    NumMaxPlanets: 'NUM_MAX_PLANETS',
    MaxInfluenceLoss: 'MAX_INFLUENCE_LOSS',
    MaxInfluenceGain: 'MAX_INFLUENCE_GAIN',
    InfluenceAwardThreshold: 'INFLUENCE_AWARD_THRESHOLD',
    SlotsUsed: 'SLOTS_USED',
    SalvageCRReward: 'SALVAGE_CR_REWARD',
    SalvageHydroReward: 'SALVAGE_HYDRO_REWARD',
    TimeToResearch: 'UNLOCK_TIME',
    XP: 'XP_AWARD',
    XPReward: 'XP_AWARD',
    TimeLimitDays: 'TIME_LIMIT_DAYS',
    MinRSLevel: 'MIN_RS_LEVEL',
    MinPlayerLevel: 'MIN_PLAYER_LEVEL',
    MinInfluence: 'MIN_INFLUENCE',
    WSMaxBSPerPlayer: 'WS_MAX_BS_PER_PLAYER',
    WSMaxOtherPerPlayer: 'WS_MAX_OTHER_PER_PLAYER',
    WSLostBSTimeCooldown: 'WS_LOST_BS_TIME_COOLDOWN',
    WSLostOtherTimeCooldown: 'WS_LOST_OTHER_TIME_COOLDOWN', // устарело
    WSJumpBSTimeCooldown: 'WS_JUMP_BS_TIME_COOLDOWN', // устарело
    WSJumpOtherTimeCooldown: 'WS_JUMP_OTHER_TIME_COOLDOWN', // устарело
    WSScoreDamageModifier: 'WS_SCORE_DAMAGE_MODIFIER',
    WSScoreMiningModifier: 'WS_SCORE_MINING_MODIFIER',
    WSScoreTransportModifier: 'WS_SCORE_TRANSPORT_MODIFIER',
    RedStarDisplayLevel: 'LVL',
    ExtraAsteroidSpawnTick: 'EXTRA_ASTEROID_SPAWN',
    ExtraAsteroidSpawnRingDistance: 'EXTRA_ASTEROID_SPAWN_RING_DISTANCE',
    ExtraAsteroidSpawnAmt: 'EXTRA_ASTEROID_SPAWN_AMT',
    WSBucketSizes: 'MODE',
    MaxWaypointsWS: 'MAX_WAYPOINTS',
    Thresholds: 'SCORE_N_THRESHOLDS',
    CollapseAreaSize: 'COLLAPSE_AREA_SIZE',
    CycleTicks: 'CYCLE_TICKS',
    StarSectorNavpoints: 'STAR_SECTOR_NAVPOINTS',
    BlueStar_CRRewardRate: 'BLS_CR_REWARD_RATE',
    BlueStar_CRRewardWinLimitPeriod: 'BLS_CR_REWARD_WIN_LIMIT_PERIOD',
    BlueStar_MaxHydroPerDayPct: 'BLS_MAX_HYDRO_PER_DAY_PCT',
    BlueStar_RankedMatchesPerDay: 'BLS_RANKED_MATCHES_PER_DAY',
    BlueStar_SPFactor: 'BLS_SP_FACTOR',
    BlueStar_HydroPctPerPos: 'BLS_HYDRO_PCT_PER_POS',
    BlueStar_Fragments: 'BLS_FRAGMENTS',
    ConceptImage: 'PORTRAIT',
    AIUpdateIntervalSeconds: 'AI_UPDATE_INTERVAL',
    ReqBank: 'REQ_BANK',
    DronesIgnoreBarrier: 'DRONES_IGNORE_BARRIER',
    RushCostModifier: 'RUSH_COST_MODIFIER',

    ...gameCharsLocKeys,
};
