export default {
    credit: [
        'UnlockPrice',
        'BCCost',
        'Cost',
        'CreditStorage',
        'CRReward',
        'BuildCost',
        'DesignUpgradeCost',
        'SectorUnlockCost',
        'TotalShipmentCRPerDay',
        'SalvageCRReward',
        'CroidAmt',
        'ColonizeCost',
        'BLSDailyCRReward',
        'CreditsPerHour',
        'ShipmentsCRValuePerDay',
    ],
    fuel: [
        'FuelUseIncrease',
        'ActivationHydro',
        'DroneHydro',
        'OnBoardHydroMax',
        'InstantHydrogenCollected',
        'HydroPerNewAsteroid',
        'HydrogenCapacity',
        'ActivationHydroOnBoard',
        'FuelStorage',
        'FuelUsePer5000Distance',
        'MoveHydrogenCostPerSector',
        'SHHydroPerDay',
        'HydrogenSearchCost',
        'HydrogenPerDay',
        'FuelPerHour',
    ],
    crystal: [
        'PriceInCrystals',
        'PCReward',
    ],
    time: [
        'UnlockTime',
        'TimeToUpgrade',
        'DesignUpgradeTime',
        'ConstructionTime',
        'ConstructionTime',
        'ConstructionTime',
        'TimeToResearch',
    ],
    flt: [
        'ShipyardCapacity',
    ],
    bls_fragments: [
        'TeleportShipmentActivationFragments',
        'FragmentCapacity',
        'BlueStar_Fragments',
    ],
    influence: [
        'Influence',
        'RegularInfuenceRange',
        'MaxInfluenceLoss',
        'MaxInfluenceGain',
    ],
    mining_route: [
        'NumSectorsToMine',
    ],
    shipments: [
        'MaxShipments',
        'ExtraTradeSlots',
        'JobCapacity',
    ],
    star_red: [
        'RSLevelReq',
    ],
    directDamageIndicator: [
        'DPS',
    ],
    areaDamageIndicator: [
        'Damage',
        'DamageWhenNeutralized',
        'AOEDamage',
        'LeapAOEAmt',
        'ImpulseDPS',
    ],
};
