export default {
    UnlockPrice: 'Стоимость изучения',
    UnlockBlueprints: 'Требуется чертежей',
    UnlockTime: 'Время изучения',
    WhiteStarScore: 'БЗ очки',
    BSScore: 'ГЗ очки',
    hyd: 'вод',
    AU: 'АЕ',
    days: 'д',
    hours: 'ч',
    min: 'мин',
    sec: 'сек',
    WS: 'БЗ',
    BS: 'ГЗ',
    RS: 'КЗ',
    typeModTrade: 'Модули торговли',
    typeModMining: 'Модули добычи',
    typeModWeapon: 'Оружейные модули',
    typeModShield: 'Модули щитов',
    typeModSupport: 'Модули поддержки',
    lvl: 'ур',
    home: 'На главную',
    content: 'Содержание',
    UpgradeCost: 'Стоимость улучшения',
    UpgradeTime: 'Время улучшения',
    NewModuleSlots: 'Тип дополнительного нового слота',
    InitialModuleLevels: 'Уровень модуля',
    MaxPerStarSystem: 'Максимальное количество на систему',
    DisableTime: 'Время отключения',
    cerbShield: 'Щит Цербера',
    cerbWeapon: 'Оружие Цербера',
    cerbSupport: 'Модуль Цербера',
    cerberus: 'Церберы',
    sections: 'Разделы',
    flagshipModules: 'Модули флагмана',
    Cost: 'Стоимость',
    PlanetTypes: 'Типы планет',
    HydrogenPerDay: 'Новый водород каждый день',
    sectors: 'Сектора',
    colonizationPlanets: 'Колонизация планет',
    lvlsPlanets: 'Улучшение планет',
    XPAward: 'Опыт',
    TimeToUpgrade: 'Время улучшения',
    MaxShipments: 'Макс. грузов',
    CreditShipmentModifier: 'Модификатор грузов',
    MaxUpgradeLevel: 'Макс. уровень',
    planets: 'Планеты',
    stars: 'Звёзды',
    ShipmentsCRValuePerDay: 'Базовая стоимость грузов в день',
    Model: 'Модель',
    SlotsUsed: 'Вес',
    SalvageCRReward: 'Кредиты за утилизацию',
    SalvageHydroReward: 'Водород за утилизацию',
    PriceInCrystals: 'Покупка за кристаллы',
    CombatArt: 'Сфера',
    UtilityArt: 'Синий кристалл',
    SupportArt: 'Тетраэдр',
    blueprints: 'Выпадение чертежей для каждого уровня',
    MaxInfluenceGain: 'Макс. влияния за победу',
    MaxInfluenceLoss: 'Макс. влияния за проигрыш',
    InfluenceAwardThreshold: 'Действия для получения влияния',
    NumMaxPlanets: 'Число макс. планет',
    NumPlayersWithAccess: 'Количество игроков',
    GhostSpawnSecs: 'Спавн «Призраков» Цербера',
    ResearchSlots: 'Количество слотов для артефактов',
    MinPlayerLevel: 'Мин. уровень игрока',
    TimeLimitDays: 'Дней на завершение',
    artLevel: 'Уровень артефакта',
    MinRSLevel: 'Мин. уровень КЗ',
    MaxRSLevel: 'Макс. уровень КЗ',
    module: 'Модуль',
    IntParam: 'Значение X',
    MoveUpdateSec: 'Задержка движения',
    BlueStar_CRRewardRate: 'Компенсация от стоимости линкора',
    BlueStar_CRRewardWinLimitPeriod: 'Перезарядка наград',
    BlueStar_MaxHydroPerDayPct: 'Максимальное вознаграждение за водород',
    BlueStar_HydroPctPerPos: 'Процент вознаграждения водородом от бака',
    BlueStar_Fragments: 'Фрагменты на позицию',
    StarSectorDPS: 'Урон звезды',
    WSBucketSizes: 'Режим',
    ScoreNThresholds: 'Действия за Тик',
    WSMaxBSPerPlayer: 'Максимум линкоров на игрока',
    WSMaxOtherPerPlayer: 'Максимальное количество кораблей другого типа на игрока',
    WSLostBSTimeCooldown: 'Перезарядка потерянного линкора',
    WSLostOtherTimeCooldown: 'Перезарядка потерянных кораблей другого типа',
    WSJumpBSTimeCooldown: 'Перезарядка после прыжка линкором',
    WSJumpOtherTimeCooldown: 'Перезарядка после прыжка другим типом корабля',
    WSScoreDamageModifier: 'WS Score модификатор битвы за',
    WSScoreMiningModifier: 'WS Score модификатор добычи',
    WSScoreTransportModifier: 'WS Score модификатор транспортировки',
    SafeInterceptorInPublicRS: 'Нейтральные Перехватчики на общедоступных КЗ',
    NoCerbBondTeleportPRS: 'Запретить использование Цербера + Узы + Телепорт на общедоступной КЗ',
    PubRSEMPReqEnemies: 'Враг в зоне ЭМИ требуется перед активацией в общедоступной КЗ',
    TID_Artifact: 'Артефакт',
    OnDestroySpawnCount: 'Количество появившихся кораблей после уничтожения',
    BarrageMaxAdditionalEnemies: 'Макс. врагов для доп. урона',
    DroneShipmentBonusMax: 'Макс. бонус',
    TeleportBreaksBond: 'Телепорт ломает Узы',
    LeapBreaksBond: 'Скачок ломает Узы',
    DestinyBreaksBond: 'Рок ломает Узы',
    BondBreaksBond: 'Узы ломают Узы',
    BondOverridesBarrier: 'Узы игнорируют Барьер',
    UnityMaxDamageIncreasePct: 'Макс. урон',
    MaxShips: 'Макс. кораблей',
    ShipToSpawn: 'Спавн корабля',
    plan: 'План',
    resetAll: 'Сбросить всё',
    resetPlan: 'Сбросить план',
    planetscalc: 'Калькулятор планет',
    other: 'Другое',
    switchAccs: 'Переключатель аккаунтов',
    open: 'Открыть',
    RelicLoad: 'Загрузка реликвии',
    TimeWarpSuppression: 'Подавление Искажения времени',
};
