name: Scheduled Merge Remote Action

on:
  push:
    branches:
      - master

  #schedule:
    #- cron: '0 14 * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master-auto             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: userXinos/HadesSpace      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master-auto          # set the branch to merge to
